import "../globals.css";
import type { Metadata } from "next";
import KalamehFont from "@/font/kalameh";
import { NextIntlClientProvider, useLocale } from "next-intl";
import { notFound } from "next/navigation";
import React from "react";
import { getLocale, Locale } from "@/data/i18n-configs";

export function generateStaticParams() {
  return [{ locale: "en" }, { locale: "fa" }];
}

const directions: any = {
  fa: "rtl",
};
export const dynamic = "force-dynamic";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = async function ({
  children,
  params,
}: {
  children: React.ReactNode;
  params: any;
}) {
  // eslint-disable-next-line react-hooks/rules-of-hooks
  const locale = useLocale();

  if (params.locale !== locale) {
    notFound();
  }

  let language;
  try {
    language = (await import(`../../languages/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }

  const { direction } = getLocale(locale as Locale);

  return (
    <html lang={locale} dir={direction}>
      <body className={`${KalamehFont.className} flex min-h-screen flex-col`}>
        <NextIntlClientProvider locale={locale} messages={language}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
};
export default RootLayout;
