import "../globals.css";
import type { Metadata } from "next";
import { NextIntlClientProvider, useLocale } from "next-intl";
import { notFound } from "next/navigation";
import React from "react";
import { getLocale, Locale, locales } from "@/data/i18n-configs";
import { MonaSans } from "@/font/mona-sans";
import { KalamehFont } from "@/font/kalameh";
import ClientSessionProvider from "@/app/ClientSessionProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "@/app/api/auth/[...nextauth]/route";
import { NextUiClientProvider } from "@/app/NextUiClientProvider";

export function generateStaticParams() {
  return locales.map(({ locale }) => ({ locale }));
}

const directions: any = {
  fa: "rtl"
};
export const dynamic = "force-dynamic";
export const metadata: Metadata = {
  title: "Sign in Page | Next js I18n",
  description: "Generated by create next app"
};

const RootLayout = async function({
                                    children,
                                    params
                                  }: {
  children: React.ReactNode;
  params: any;
}) {
  // eslint-disable-next-line react-hooks/rules-of-hooks
  const locale = useLocale();

  if (params.locale !== locale) {
    notFound();
  }

  let language;
  try {
    language = (await import(`../../languages/${locale}.json`)).default;
  } catch (error) {
    notFound();
  }

  const { direction } = getLocale(locale as Locale);
  const session = await getServerSession(authOptions);
  return (
    <html lang={locale} dir={direction} className={"dark"}>

    <body
      className={`${MonaSans.variable} ${KalamehFont.variable}`}
    >
    <ClientSessionProvider session={session}>
      <NextUiClientProvider>
        <div className="flex flex-col font-mona-sans-kalameh min-h-screen">
          <NextIntlClientProvider locale={locale} messages={language}>
            {children}
          </NextIntlClientProvider>
        </div>
      </NextUiClientProvider>
    </ClientSessionProvider>

    </body>

    </html>
  );
};
export default RootLayout;
